name: Filter Channels

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  filter:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - run: pip install requests

    - run: python filter.py

    - run: |
        git config --global user.name "BOT"
        git config --global user.email "bot@github.com"
        git add KASSSSKASSSK.m3u
        git commit -m "Update alive channels" || echo "No changes"
        git push
