name: Filter Channels

on:
  workflow_dispatch:   # لتشغيله يدويًا
  schedule:
    - cron: "*/10 * * * *"  # تشغيل كل 30 دقيقة

permissions:
  contents: write  # مهم جدًا للكتابة على المستودع

jobs:
  filter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests

      - name: Run filter script
        run: python filter.py

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # جلب التحديثات الأخيرة للتأكد من مزامنة الفرع
          git fetch origin main
          git checkout main
          git reset --hard origin/main

          # إضافة الملف الجديد أو المحدث
          git add s7.m3u

          # commit فقط إذا هناك تغييرات
          git diff --cached --quiet || git commit -m "Update alive channels"

          # رفع التغييرات مباشرة باستخدام PAT
          git push https://$PAT_TOKEN@github.com/kakagoosse856/1221554 main --force
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
