name: Update Alive Channels

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *" # كل 30 دقيقة

permissions:
  contents: write

concurrency:
  group: update-alive-channels
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 streamlink pytz

      # 4️⃣ Run M3U Collector
      - name: Run M3U Collector
        run: |
          python collector.py
        env:
          PYTHONUNBUFFERED: 1

      # 5️⃣ Run filter.py to generate best streams
      - name: Run filter.py
        run: |
          python filter.py

      # 6️⃣ Commit & push changes safely
      - name: Commit & Push Changes
        run: |
          git config user.name "BOT"
          git config user.email "bot@github.com"

          git fetch origin main
          git reset --hard origin/main

          git add *.m3u *.json *.txt || true

          if git diff --staged --quiet; then
            echo "No changes detected"
            exit 0
          fi

          git commit -m "Update alive channels"
          git push origin HEAD:main
